// @ts-check
import { defineConfig } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';
import tailwindcss from '@tailwindcss/vite';
import { copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

/**
 * /CREDITS.md is generated by src/pages/CREDITS.md.ts, so it lands in
 * dist/ with the rest of the build. PRD §2.3 wants it readable in the
 * repository too — a licence file nobody can find before deploying is not
 * doing its job — so the built copy is mirrored to the project root.
 *
 * Copying the build output rather than writing a second generator keeps the
 * "cannot drift" guarantee: there is still exactly one thing that produces it.
 */
function mirrorCredits() {
  return {
    name: 'mirror-credits',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const from = new URL('CREDITS.md', dir);
        const to = new URL('./CREDITS.md', import.meta.url);
        await copyFile(fileURLToPath(from), fileURLToPath(to));
        logger.info('CREDITS.md mirrored to the project root');
      },
    },
  };
}

// Concept site. Deliberately NOT the practice's real domain (PRD §4).
export default defineConfig({
  site: 'https://coventry-dental-concept.pages.dev',
  output: 'static',
  adapter: cloudflare({ imageService: 'compile' }),
  integrations: [mirrorCredits()],
  prefetch: false,
  build: { inlineStylesheets: 'always' },
  vite: {
    plugins: [tailwindcss()],
  },
});
